version: '3'
services:
    redis:
        image: redis:5
        ports:
            - 6379:6379
        command: redis-server
        restart: on-failure
        volumes:
            - redis:/data
volumes:
    redis: